### ISSUE TITLE
C2ME ThreadLocalRandom accessed from a different thread errors - CaveSpiderMixin

### ISSUE THREAD

**Issue by gvancamp** [sf-inc/sihywtcamd_extensions#1]
[c2me-worker-2/ERROR]: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-worker-2)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code.
Possible solutions:
  - Find possible causes in the stack trace below and
    - if caused by another mod, report this to the corresponding mod authors
    - if no other mods are involved, report this to C2ME

java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-worker-2)
        at knot/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55) ~[c2me-fixes-worldgen-threading-is0.299+1.21.1-34b0bb1feeddc57.jar:?]
        at knot/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[c2me-fixes-worldgen-threading-is0.299+1.21.1-34b0bb1feeddc57.jar:?]
        at knot/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:86) ~[c2me-fixes-worldgen-threading-is0.299+1.21.1-34b0bb1feeddc57.jar:?]
        at knot/net.minecraft.class_6566.method_43057(class_6566.java:56) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1299.method_5888(net/minecraft/class_1299.java:440) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1299.method_5899(net/minecraft/class_1299.java:413) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1299.method_47821(net/minecraft/class_1299.java:408) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1549.handler$ehn000$sihywtcamd_extensions$spawnBaby(com/github/charlyb01/sihywtcamd_extensions/mixin/spider/CaveSpiderMixin.java [sihywtcamd_extensions.mixins.json]:36) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_1549.method_5943(net/minecraft/class_1549.java:56) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3499.method_17917(net/minecraft/class_3499.java:427) ~[server-intermediary.jar:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at knot/net.minecraft.class_3499.method_15179(net/minecraft/class_3499.java:422) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3499.method_15172(net/minecraft/class_3499.java:347) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3781.method_16626(net/minecraft/class_3781.java:143) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3790.method_27236(net/minecraft/class_3790.java:98) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3790.method_14931(net/minecraft/class_3790.java:94) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3449.mixinextras$bridge$method_14931$23(class_3449.java) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3449.wrapOperation$cjh000$frozenlib$frozenLib$placeInChunkB(net/frozenblock/lib/worldgen/structure/mixin/StructureStartMixin.java [mixin/frozenlib.worldgen.structure.mixins.json]:121) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3449.method_14974(net/minecraft/class_3449.java:100) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_2794.method_38265(net/minecraft/class_2794.java:324) ~[server-intermediary.jar:?]
        at knot/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar:?]
        at knot/net.minecraft.class_2794.method_12102(net/minecraft/class_2794.java:323) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_9310.method_57610(net/minecraft/class_9310.java:103) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_9770.mixinextras$bridge$doWork$14(class_9770.java) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_9770.wrapOperation$bcj000$c2me-opts-chunk-access$runGenerationTask(com/ishland/c2me/opts/chunk_access/mixin/region_capture/MixinChunkGenerationStep.java [c2me-opts-chunk-access.mixins.json]:26) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_9770.method_60560(net/minecraft/class_9770.java:33) ~[server-intermediary.jar:?]
        at knot/com.ishland.c2me.rewrites.chunksystem.common.statuses.VanillaWorldGenerationDelegate.lambda$upgradeToThis$8(VanillaWorldGenerationDelegate.java:123) ~[c2me-rewrites-chunk-system-0.3.0.299+1.21.1-c95ef437b6e3336f.jar:?]
        at knot/com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) [c2me-base-0.3.0+alpha.0.299+1.21.1-4ad1ca956dec760d.jar:?]
        at knot/com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:57) [c2me-base-0.3.0+alpha.0.299+1.21.1-4ad1ca956dec760d.jar:?]
        at knot/com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:27) [c2me-base-0.3.0+alpha.0.299+1.21.1-4ad1ca956dec760d.jar:?]

**Comment by brett-falck** [comment]
I just ran into this issue on my server too if anyone has any fixes. Poking through the stack trace, could it be related to this bit?:

 at knot/net.minecraft.class_1549.handler$ehn000$sihywtcamd_extensions$spawnBaby(com/github/charlyb01/sihywtcamd_extensions/mixin/spider/CaveSpiderMixin.java [sihywtcamd_extensions.mixins.json]:36) ~[server-intermediary.jar:?]
 
 which might also be related to this bit: https://github.com/sf-inc/sihywtcamd_extensions/blob/7639dcd1312e178b7f769a0fe0aaf4d696b8deb7/src/main/java/com/github/charlyb01/sihywtcamd_extensions/mixin/spider/CaveSpiderMixin.java#L32

**Comment by Onewingseraphim** [comment]
I just ran into this same issue on fabric 1.21.1
